# Generated by Django 3.0 on 2019-12-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.DateField(blank=True),
        ),
    ]
