# Generated by Django 3.0 on 2019-12-24 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genres', '0001_initial'),
        ('suppliers', '0001_initial'),
        ('categories', '0001_initial'),
        ('brands', '0002_auto_20191224_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('price_purchase', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('price_sales', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('price_profit', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('date_expired', models.DateField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('image', models.TextField(blank=True)),
                ('created_at', models.DateField(blank=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='brands.Brand')),
                ('categories', models.ManyToManyField(to='categories.Category')),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='genres.Type')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.Supplier')),
            ],
        ),
    ]
